### ISSUE TITLE
Source CAD files

### ISSUE THREAD

**Issue by stevexyz** [victorlucachi/void30#1]
Is possible you to publish also the source CAD file to be able to modify it?

**Comment by stevexyz** [comment]
Seems completed but I was not able to find the source CAD files (just outputs for 3d printers)

**Comment by victorlucachi** [comment]
> Seems completed but I was not able to find the source CAD files (just outputs for 3d printers)

yes, hello steve. step files have been uploaded, and for simple mods they are easier to edit/work with than mesh/stl. I am not publishing my f3d files, the models are easy enough to replicate from scratch, and if you have any particular questions in mind that I might be able to answer you can always drop me a line.

**Comment by stevexyz** [comment]
Ciao Victor! :)

> ... if you have any particular questions in mind that I might be able to answer you can always drop me a line.

My idea was to slightly modify them to be able to create something like this: https://github.com/stevexyz/qmk_firmware/blob/master/stevexyz28custom.jpg

The space might be put between v and b as in alpha, probably better not only aestethically but also for functionality as number pad - see super micro gherkin keymap in case: something like this [more ortho](http://www.keyboard-layout-editor.com/##@@_x:0.25%3B&=Q&=W&=E&=R&=T&=Y&=U&=I&=O&=P%3B&@_x:0.25%3B&=A&=S&=D&=F&=G&=H&=J&=K&=L&_x:0.25&w:1.25&h:2&w2:1.5&h2:1&x2:-0.25%3B&=Enter%3B&@_x:0.75%3B&=Z&=X&=C&=V&_a:7&w:1.75%3B&=&_a:4%3B&=B&=N&=M) or like this [more slanted](http://www.keyboard-layout-editor.com/##@@=Q&=W&=E&=R&=T&=Y&=U&=I&=O&=P%3B&@_x:0.25%3B&=A&=S&=D&=F&=G&=H&=J&=K&=L&_x:0.25&w:1.25&h:2&w2:1.5&h2:1&x2:-0.25%3B&=Enter%3B&@_x:0.5%3B&=Z&=X&=C&=V&_a:7&w:2%3B&=&_a:4%3B&=B&=N&=M)
